Basic_formUI = Ext.extend(Ext.Panel,{
  "padding": 5,
  "title": "Basic Form",
  "autoHeight": true,
  "autoDestroy": true,
  "id": "viewport",
  "style": "position: auto; margin: 0 auto; width: 960px; margin-top: 30px;\n",
  initComponent: function(){
    Ext.applyIf(this,
    {
  "xtype":"panel",
  "items":[
    {
      "xtype":"container",
      "layout":"fit",
      "autoWidth":true,
      "autoDestroy":true,
      "autoHeight":true,
      "style":"{height: 100%; margin: 0em 0em;}",
      "defaults":{
        "margins":"0 0"
      },
      "items":[
        {
          "xtype":"form",
          "autoHeight":true,
          "layout":"form",
          "labelWidth":200,
          "labelAlign":"right",
          "border":false,
          "title":null,
          "autoDestroy":true,
          "id":"frm",
          "frame":true,
          "fileUpload":true,
          "ref":"../frm",
          "items":[
            {
              "xtype":"fieldset",
              "layout":"form",
              "animCollapse":true,
              "labelAlign":"right",
              "autoHeight":true,
              "title":"Basic Form",
              "autoDestroy":true,
              "id":"basic-form",
              "labelWidth":78,
              "ref":"../../basicForm",
              "items":[
                {
                  "xtype":"textfield",
                  "width":150,
                  "autoCreate":{
                    "tag":"input",
                    "type":"text",
                    "autocomplete":"off"
                  },
                  "submitValue":true,
                  "name":"text",
                  "fieldLabel":"Text",
                  "autoDestroy":true,
                  "id":"text",
                  "ref":"../../../text"
                },
                {
                  "xtype":"numberfield",
                  "width":150,
                  "decimalPrecision":2,
                  "decimalSeparator":".",
                  "allowDecimal":true,
                  "allowNegative":false,
                  "cls":"number",
                  "submitValue":true,
                  "name":"number",
                  "fieldLabel":"Number",
                  "autoDestroy":true,
                  "id":"number",
                  "ref":"../../../number"
                },
                {
                  "xtype":"textfield",
                  "width":150,
                  "cls":"number",
                  "plugins":[
                    {
                      "ptype":"currency"
                    },
                    {
                      "ptype":"multiple_validations"
                    }
                  ],
                  "currencyConfig":{
                  },
                  "submitValue":true,
                  "name":"money",
                  "fieldLabel":"Money",
                  "autoDestroy":true,
                  "id":"money",
                  "ref":"../../../money"
                },
                {
                  "xtype":"textfield",
                  "width":150,
                  "cls":"number",
                  "plugins":[
                    {
                      "ptype":"currency"
                    }
                  ],
                  "currencyConfig":{
                    "currencySymbol":""
                  },
                  "submitValue":true,
                  "name":"numeric",
                  "fieldLabel":"Numeric",
                  "autoDestroy":true,
                  "id":"numeric",
                  "ref":"../../../numeric"
                },
                {
                  "xtype":"combo",
                  "width":150,
                  "store":[
                    "opt1",
                    "opt2",
                    "opt3"
                  ],
                  "minChars":2,
                  "valueField":"key",
                  "displayField":"pair",
                  "cls":"combo",
                  "lazyInit":false,
                  "mode":"local",
                  "triggerAction":"all",
                  "loadingText":"Loading ...",
                  "submitValue":true,
                  "name":"combo",
                  "fieldLabel":"Combo",
                  "emptyText":"Select Combo",
                  "autoDestroy":true,
                  "id":"combo",
                  "ref":"../../../combo"
                },
                {
                  "xtype":"datefield",
                  "width":100,
                  "cls":"date",
                  "submitValue":true,
                  "name":"date",
                  "fieldLabel":"Date",
                  "autoDestroy":true,
                  "id":"date",
                  "ref":"../../../date"
                },
                {
                  "xtype":"timefield",
                  "width":100,
                  "cls":"time",
                  "submitValue":true,
                  "name":"time",
                  "fieldLabel":"Time",
                  "autoDestroy":true,
                  "id":"time",
                  "ref":"../../../time"
                },
                {
                  "xtype":"fileuploadfield",
                  "width":250,
                  "buttonText":"Browse",
                  "submitValue":true,
                  "name":"upload",
                  "fieldLabel":"Upload",
                  "autoDestroy":true,
                  "id":"upload",
                  "ref":"../../../upload"
                },
                {
                  "xtype":"compositefield",
                  "submitValue":true,
                  "name":"composite",
                  "fieldLabel":"Composite",
                  "autoDestroy":true,
                  "id":"composite",
                  "layout":"form",
                  "labelWidth":85,
                  "ref":"../../../composite",
                  "items":[
                    {
                      "xtype":"textfield",
                      "width":150,
                      "autoCreate":{
                        "tag":"input",
                        "type":"text",
                        "autocomplete":"off"
                      },
                      "submitValue":true,
                      "name":"composit_a",
                      "fieldLabel":"Composit A",
                      "autoDestroy":true,
                      "id":"composit-a",
                      "value":"ReadOnly",
                      "readOnly":true,
                      "ref":"../../../../compositA"
                    },
                    {
                      "xtype":"textfield",
                      "width":150,
                      "autoCreate":{
                        "tag":"input",
                        "type":"text",
                        "autocomplete":"off"
                      },
                      "submitValue":true,
                      "name":"composit_b",
                      "fieldLabel":"Composit B",
                      "autoDestroy":true,
                      "id":"composit-b",
                      "disabled":true,
                      "value":"Disabled",
                      "ref":"../../../../compositB"
                    },
                    {
                      "xtype":"button",
                      "text":"Nothing",
                      "padding":"0.2em 0.2em",
                      "style":"{font-weight: bold;}",
                      "autoDestroy":true,
                      "id":"nothing",
                      "ref":"../../../../nothing"
                    }
                  ]
                },
                {
                  "xtype":"checkboxgroup",
                  "submitValue":true,
                  "name":"chk_group",
                  "fieldLabel":"Chk Group",
                  "autoDestroy":true,
                  "id":"chk-group",
                  "layout":"form",
                  "labelWidth":10,
                  "width":128,
                  "ref":"../../../chkGroup",
                  "items":[
                    {
                      "xtype":"checkbox",
                      "hideLabel":true,
                      "cls":"checkbox",
                      "submitValue":true,
                      "name":"check_a",
                      "boxLabel":"Check A",
                      "autoDestroy":true,
                      "id":"check-a",
                      "width":79,
                      "ref":"../../../../checkA"
                    },
                    {
                      "xtype":"checkbox",
                      "hideLabel":true,
                      "cls":"checkbox",
                      "submitValue":true,
                      "name":"check_b",
                      "boxLabel":"Check B",
                      "autoDestroy":true,
                      "id":"check-b",
                      "width":79,
                      "ref":"../../../../checkB"
                    }
                  ]
                },
                {
                  "xtype":"radiogroup",
                  "submitValue":true,
                  "name":"radio",
                  "boxLabel":"Radio",
                  "fieldLabel":"Radio",
                  "autoDestroy":true,
                  "id":"radio",
                  "layout":"form",
                  "labelWidth":10,
                  "width":142,
                  "ref":"../../../radio",
                  "items":[
                    {
                      "xtype":"radio",
                      "labelWidth":100,
                      "hideLabel":true,
                      "submitValue":true,
                      "name":"radio",
                      "boxLabel":"Chanel A",
                      "inputValue":"chanel_a",
                      "autoDestroy":true,
                      "id":"chanel-a",
                      "width":86,
                      "ref":"../../../../chanelA"
                    },
                    {
                      "xtype":"radio",
                      "labelWidth":100,
                      "hideLabel":true,
                      "submitValue":true,
                      "name":"radio",
                      "boxLabel":"Chanel B",
                      "inputValue":"chanel_b",
                      "autoDestroy":true,
                      "id":"chanel-b",
                      "default":true,
                      "width":86,
                      "ref":"../../../../chanelB"
                    }
                  ]
                },
                {
                  "xtype":"textarea",
                  "width":150,
                  "submitValue":true,
                  "name":"text_area",
                  "fieldLabel":"Text Area",
                  "autoDestroy":true,
                  "id":"text-area",
                  "ref":"../../../textArea"
                },
                {
                  "xtype":"container",
                  "layout":"auto",
                  "autoWidth":true,
                  "autoDestroy":true,
                  "html":"<hr/>"
                },
                {
                  "xtype":"container",
                  "layout":"auto",
                  "autoWidth":true,
                  "autoDestroy":true,
                  "id":"button-wrapper",
                  "style":"margin-left: 80px;\n",
                  "ref":"../../../buttonWrapper",
                  "items":[
                    {
                      "xtype":"container",
                      "layout":"hbox",
                      "autoWidth":true,
                      "autoDestroy":true,
                      "layoutConfig":{
                        "pack":"start",
                        "align":"stretchmax"
                      },
                      "defaults":{
                        "margins":"0 2.5"
                      },
                      "items":[
                        {
                          "xtype":"container",
                          "layout":"anchor",
                          "autoWidth":true,
                          "autoDestroy":true,
                          "renderHidden":false,
                          "autoHeight":true,
                          "margins":"0 0",
                          "items":[
                            {
                              "xtype":"button",
                              "text":"Submit",
                              "padding":"0.2em 0.2em",
                              "style":"{font-weight: bold;}",
                              "autoDestroy":true,
                              "id":"submit",
                              "width":100,
                              "onClick":function(){  var params = Ext.getCmp('frm').               serializeObject();  var txt = '';  _.each(params, function(v, k){    txt += (k + ' => ' + v);    txt += ', ';  });  alert(txt);},
                              "ref":"../../../../../../submit"
                            }
                          ]
                        },
                        {
                          "xtype":"container",
                          "layout":"anchor",
                          "autoWidth":true,
                          "autoDestroy":true,
                          "renderHidden":false,
                          "autoHeight":true,
                          "style":"{ height: 100%; margin: 0em 0em; }",
                          "defaults":{
                            "margins":"0 0"
                          },
                          "items":[
                            {
                              "xtype":"button",
                              "text":"Cancel",
                              "padding":"0.2em 0.2em",
                              "style":"{font-weight: bold;}",
                              "autoDestroy":true,
                              "id":"cancel",
                              "ref":"../../../../../../cancel"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
});
    Basic_formUI.superclass.initComponent.call(this);
    var self = this;
    
  }
});